version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: paybuddy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: paybuddy_db
      POSTGRES_USER: paybuddy
      POSTGRES_PASSWORD: paybuddy123
    ports:
      - "5433:5432"
    volumes:
      - paybuddy_pgdata:/var/lib/postgresql/data

volumes:
  paybuddy_pgdata: