spring.datasource.username=sharedexpense_user
spring.datasource.password=Student1234
app.jwt.secret=ILoveBangtanSonyeondan!613
spring.mail.username=joonsclare@gmail.com
spring.mail.password=htqq mtnp fbqq nlvd