# APP
spring.application.name=shared-expense-app

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5433/paybuddy_db
spring.datasource.username=paybuddy
spring.datasource.password=paybuddy123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=
app.jwt.expiration-ms=604800000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

server.address=0.0.0.0